version: '3'

services:
  web:
    build: ./api
    env_file: 
      - ./environments/hightechcross.env
    image: docker.alveona.ml/hightechcross/hightechcross_web:latest
    # volumes: # for local debugging to avoid rebuilding
    #   - ./api/app:/var/www/app/app
    expose:
      - "5000"
  nginx:
    build: ./nginx
    image: docker.alveona.ml/hightechcross/hightechcross_nginx:latest
    ports:
      - 5000:8000
    depends_on:
      - web
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017